### ISSUE TITLE
Optionally install dependencies

### ISSUE THREAD

**Issue by pakokrew** [rocket-pool/smartnode-install#6]
Currently the setup script install all the required dependencies to be running a rocket pool node. 

However, I think could be great to disable the "Install dependencies" step, so that a pre-configured computer don't see its configuration touched. 

A computer could already have docker and the other dependencies alreay installed and may do not want its configuration changed by commands such as `sudo apt-install upgrade` `sudo groupadd docker`

Just list the dependencies required (apt-transport-https ca-certificates curl gnupg-agent software-properties-common, docker-ce, docker-compose)

**Comment by moles1** [comment]
Hi @pakokrew , that sounds like a great suggestion but we would like to keep the installation script fairly light for the time being (with minimal flags etc), and still need it to cater to users who might find it difficult to install some of these things manually.

A good solution might be if we add a "manual installation" section to our documentation and refer more advanced users (who want a custom installation) to this instead of using the installation script. Would this suit your use case well?

Thanks! :)
Jake

**Comment by pakokrew** [comment]
+1 for keeping it simple for now

anyway an advanced user could just edit the setup script which is quite clear, and remove what he doesnt want. 

thanks for the response ;)

**Comment by moles1** [comment]
No problem! Good point re: advanced users curling the script and checking/modifying it before running it (which I imagine many will do anyway). We'll update the docs too regardless, I'll leave this open until then.

**Comment by moles1** [comment]
Optional installation of OS dependencies (inc. docker & docker-compose) now available via `-d` flag
