### ISSUE TITLE
Where can I find an example of uset-setting.yml

### ISSUE THREAD

**Issue by jakubgs** [rocket-pool/smartnode-install#76]
It appears in the [1.3.0](https://github.com/rocket-pool/smartnode-install/releases/tag/v1.3.0) release the example `settins.yml` and `config.yml` files were removed. Specifically in this commit: https://github.com/rocket-pool/smartnode-install/commit/fe382430

The release notes state that:

>Removed `config.yml` and `settings.yml`; there will now be a single file with all user-modifiable settings called `user-settings.yml`.

But no such `user-settings.yml` file exists in this repo:
https://github.com/rocket-pool/smartnode-install/search?q=user-settings.yml

And the link to the migration guide in the release just gives 404:
https://docs.rocketpool.net/guides/node/v1.3-update.html

We've been running `1.0.0` so far with our own Ansible role to set things up: https://github.com/status-im/infra-role-rocketpool
And now that I'm trying to upgrade to `1.5.0` I'm a little confuse as to where I'm supposed to find an example `user-setting.yml`.

**Comment by jclapis** [comment]
Hi! I encourage you to come to the Support channel in our Discord server (http://discord.gg/rocketpool) for real-time help with questions like these, but I'll try to answer here.

So v1.0.0 is obviously very out of date, and no longer supported. Quite a bit has changed since then. I would encourage you to keep your setup up-to-date with the latest releases, *especially* going into the merge where things like the Fee Recipient matter greatly and having the latest version with bug fixes is crucial.

To start, the migration guide from v1.0.0 to v1.3 has been moved to here: https://docs.rocketpool.net/guides/legacy/v1.3-update.html

That will cover *some* of the changes, but v1.5 has more things that go beyond that guide. You will also want to look at the v1.5 migration guide most appropriate for you: https://docs.rocketpool.net/guides/redstone/whats-new.html

Anyway, once you grab the new CLI, the intended route is to use the Terminal UI from `rocketpool service config` to generate a `user-settings.yml` file that's tailored to your environment. If you are running headlessly and can't access the TUI, no worries.
You can use `rocketpool service config` in headless mode to pass in your values for each setting and have it generate the file for you. Here's a guide on how to do that: https://docs.rocketpool.net/guides/node/config-docker.html#configuring-via-the-command-line

To get a brief description of each line item and lists of valid values per setting, use `rocketpool service config --help`.
For *really* detailed information about each one, use `rocketpool service get-config-yaml`.

If you can't run it to generate the configuration files at runtime and you really need a static config file you can preload, I've attached an example from one of my Native nodes here:

[user-settings.yml.zip](https://github.com/rocket-pool/smartnode-install/files/9356903/user-settings.yml.zip)

Use the above to modify it accordingly. Let me know how that works for you.

**Comment by jakubgs** [comment]
Thanks for the explanation and the up-to-date migration links. I appreciate you adding extra detail in your answer and the example config, which will surely come in handy. Though it still might be good to have such example config somewhere in the repo.

I'll look into it and get back to you. I prefer to deploy things my own way instead of using other people's automations because I want to actually understand the parts and how they work, rather than just deploy a black box.

Cheers!

**Comment by jakubgs** [comment]
Thanks. One question: What's the difference between those three flags:
```
   --consensusClient value  Select which Consensus client you would like to use.
                            Type: choice
                            Options: lighthouse, nimbus, prysm, teku
 (default: "nimbus")

   --externalConsensusClient value  Select which Consensus client your externally managed client is.
                                    Type: choice
                                    Options: lighthouse, prysm, teku
 (default: "lighthouse")

   --native-consensusClient value   Select which Consensus client you are using / will use.
                                    Type: choice
                                    Options: lighthouse, nimbus, prysm, teku
 (default: "nimbus")
```
Should one be used and not the others if I'm running my node myself with systemd. Or all three?

**Comment by jakubgs** [comment]
Closing this as no longer relevant.
